const fs = require("fs");
const h = fs.readFileSync("C:/Users/xylt2/Documents/anothereden/src/pages/character-detail/index.html", "utf-8");
console.log("Count of 基础属性:", (h.match(/基础属性/g) || []).length);
console.log("Count of 天冥奖励:", (h.match(/天冥奖励/g) || []).length);
console.log("Count of 技能</div>:", (h.match(/技能<\/div>/g) || []).length);
console.log("Count of 星导觉醒:", (h.match(/星导觉醒/g) || []).length);
console.log("Count of <!DOCTYPE:", (h.match(/<!DOCTYPE/g) || []).length);
console.log("Count of <div id=\"app\">:", (h.match(/<div id="app">/g) || []).length);
console.log("Has rowspan:", h.includes("rowspan"));
console.log("Has 战斗宣言 header:", h.includes("战斗宣言</th>"));
console.log("Empty td test:", h.includes("colspan=\"3\"></td>"));
console.log("File size:", h.length);
