const fs = require("fs");
const h = fs.readFileSync("C:/Users/xylt2/Documents/anothereden/src/pages/character-detail/index.html", "utf-8");
console.log("Count of 基础属性:", (h.match(/基础属性/g) || []).length);
console.log("Count of 天冥奖励:", (h.match(/天冥奖励/g) || []).length);
console.log("Count of 技能:", (h.match(/技能<\/div>/g) || []).length);
console.log("Count of 星导觉醒:", (h.match(/星导觉醒/g) || []).length);
console.log("Count of <div id=\"app\">:", (h.match(/<div id="app">/g) || []).length);
console.log("Count of <!DOCTYPE:", (h.match(/<!DOCTYPE/g) || []).length);
console.log("Count of </main>:", (h.match(/<\/main>/g) || []).length);
console.log("Has v-if st=== 战斗宣言:", h.includes('v-if="st ==='));
console.log("Has 角色未找到:", h.includes("角色未找到"));
console.log("File size:", h.length);
